### ISSUE TITLE
Создать экран входа.

### ISSUE THREAD

**Issue by Rabort** [Rabort/Rabort.github.io#2]
Планирую создать экран входа (личный кабинет). А дальше надо заняться самим сайтом, накидай идей что сделать надо.

**Comment by lolmak** [comment]
Пока что рано личный кабинет, я думаю. Это уже когда у нас учебный план будет программа генерировать, можно будет. Сейчас нам нужно будет бахнуть так, чтобы сайт проверял файл на формат excel, txt и т.п. и не давал загрузить бинарные файлы, exe, картинки и т.п.

**Comment by Rabort** [comment]
> Пока что рано личный кабинет, я думаю. Это уже когда у нас учебный план будет программа генерировать, можно будет. Сейчас нам нужно будет бахнуть так, чтобы сайт проверял файл на формат excel, txt и т.п. и не давал загрузить бинарные файлы, exe, картинки и т.п.
